version: "3.9"

services:
  postgres:
    image: postgres:14.0
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: casablanca
      POSTGRES_DB: toys_db
      POSTGRES_USER: toy
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
